### ISSUE TITLE
Roadmap of nBallerina development 2021

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/nballerina-cpp#84]
**Description:**
This issue captures the high level roadmap planned for nBallerina development work for 2021.

- [ ] **Support for Ballerina types**
     - Storing values without storage identity and values with storage identity (Reference values))

- [ ] **Runtime type checker** 

- [ ] **Langlib modules** 
     - https://github.com/ballerina-platform/ballerina-spec/tree/master/lang/lib

- [ ] **Interoperability** 

    - Ability to use existing static C libraries 
    - Packaging libraries with Balo and pushing them to central. 
        - Balo spec supports packaging platform-specific libraries 
    - jBallerina FFI layer design 
       - https://docs.google.com/document/d/1hlKSd-tQQfr8tJVvHUor7zOIqHbztqu2jqihnK7IUhw/edit
       - https://github.com/ballerina-platform/ballerina-lang/blob/master/langlib/jballerina.java/src/main/ballerina/annotations.bal

- [ ] **Integrate nBallerina backend to the `bal` tool**
    - `bal build `
    - The idea here is to have two separate distributions 
        - jballerina 
        - nballerina

- [ ] **Support for importing modules**  
    - Should be able to write a program with multiple modules 
      - Module init, start phases

- [ ] **Support for strands** 
    - We can start with a single-threaded strand scheduler 
      - This allows us to support all the concurrency features in the language. 
    - Later improve the scheduler to handle multiple OS threads.

- [ ] **Automatic memory management** 
    - Consider readonly and isolatedness
    - Handling graphs with cycles 

- [ ] **Debugging**

- [ ] **Support for services** 
    - We can start with HTTP service and client support

**Comment by sameerajayasoma** [comment]
Let's remove the proposed reference counting solution from this. My initial proposal does not work.
